# Generated by Django 6.0.3 on 2026-04-03 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['deadline'], 'verbose_name': 'task', 'verbose_name_plural': 'tasks'},
        ),
        migrations.AlterModelOptions(
            name='tasktype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'ordering': ['username'], 'verbose_name': 'worker', 'verbose_name_plural': 'workers'},
        ),
    ]
